#!/bin/sh
## The following to run programs in the current working directory
#$ -cwd
## Specify a queue
#$ -q batchq
## The following two lines will send an email notification when the job is
## Ended/Aborted/Suspended - Please replace "UserName" with your own username.
#$ -M zyhu
#$ -m aes

## annotate CpG with the genomic element annotation
## Zhiyuan Hu
## 20 May 2020

module load bedtools/2.25.0 

## the mESC_cStates_HMM.bed.gz was generated by R/genomic_element_analysis.R

## sort HMM file first (don't need to rerun this)
## bed=/home/obgynae/zyhu/projects/taps/ref/mESC_cStates_HMM.bed.gz
## out=/home/obgynae/zyhu/projects/taps/ref/mESC_cStates_HMM_sorted.bed
## zcat $bed | sort -k1,1 -k2,2n > $out
## gzip $out

## sort caps methy data
dir=/home/obgynae/zyhu/projects/taps/analysis_caps/methy_data
bed=${dir}/caps_CpG_mods.bed.gz
out=${dir}/caps_CpG_mods_sorted.bed
zcat $bed | sort -k1,1 -k2,2n > $out
gzip $out

## annoate caps methy data
dir=/home/obgynae/zyhu/projects/taps/analysis_caps/methy_data
bedb=/home/obgynae/zyhu/projects/taps/ref/mESC_cStates_HMM_sorted.bed.gz
beda=${dir}/caps_CpG_mods_sorted.bed.gz
out=${dir}/caps_CpG_mods_annotated.bed.gz
bedtools intersect -sorted -wo -a $beda -b $bedb | gzip > $out

## zcat caps_CpG_mods_annotated.bed.gz | grep 'chr2' | head -100000 | gzip > caps_CpG_mods_annotated_chr2_top100k.bed.gz

##############

## sort tapsbeta methy data
## dir=/home/obgynae/zyhu/projects/taps/analysis_caps/methy_data
## bed=${dir}/tapsbeta_CpG_mods.bed.gz
## out=${dir}/tapsbeta_CpG_mods_sorted.bed.gz
## zcat $bed | sort -k1,1 -k2,2n | gzip > $out


## annotate tapsbeta methy data
## beda=${dir}/tapsbeta_CpG_mods.bed.gz
## bedb=/home/obgynae/zyhu/projects/taps/ref/mESC_cStates_HMM_sorted.bed.gz
## out=${dir}/tapsbeta_CpG_mods_annotated.bed.gz
## bedtools intersect -sorted -wao -a $beda -b $bedb | gzip > $out

#############

## annotate TAB-seq methy data
dir=/home/obgynae/zyhu/projects/taps/analysis_caps/methy_data
beda=${dir}/tabseq_CpG_mods.bed.gz
bedb=/home/obgynae/zyhu/projects/taps/ref/mESC_cStates_HMM_sorted.bed.gz
out=${dir}/tabseq_CpG_mods_annotated.bed.gz
bedtools intersect -wao -a $beda -b $bedb | gzip > $out


## run R script

module load R/3.6.0-newgcc

Rscript $HOME/projects/taps/analysis_caps/R/caps_genomic_element_analysis.R 2>&1 | \
tee > $HOME/projects/taps/analysis_caps/R/logs/caps_genomic_element_analysis_20200726.log



